name: pathaligner
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_1
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.9=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - charset-normalizer==2.0.12
    - click==8.1.0
    - cmappy==4.0.1
    - datasets==2.6.1
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==0.8.3
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - h5py==3.6.0
    - huggingface-hub==0.4.0
    - importlib-resources==5.6.0
    - ipykernel==6.10.0
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.1
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.10
    - packaging==21.3
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.28
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==7.0.0
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - regex==2022.3.15
    - responses==0.18.0
    - sacremoses==0.0.49
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - send2trash==1.8.0
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - torchaudio==0.11.0+cu113
    - torchvision==0.12.0+cu113
    - tornado==6.1
    - tqdm==4.63.1
    - traitlets==5.1.1
    - transformers==4.17.0
    - typing-extensions==4.2.0
    - wandb==0.12.16
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.7.0
